version: 1

update_configs:
  - package_manger: "javascript"
    directory: "/"
    # How often to check for non-security updates and when to create pull
    # requests. Security updates are always created as soon as possible.
    update_schedule: "daily"
    allowed_updates:
      # Always allow security updates.
      - match:
          dependency_type: "all"
          update_type: "security"
